#!/bin/sh

# mpv-android-argparse
#
# Github: https://github.com/TheGlockMisc/mpv-android-argparse

VERSION="v0.1.1"

app_readable_dir="/storage/emulated/0/mpv"
app_readable_file="${app_readable_dir}/mpv.tmp"
[ ! -t 0 ] && stdinurl="$(awk '{print $0}')"

# Input Colors
err(){
	printf "\033[38;5;1m%b\033[0m\n" "${1}" >&2
	exit 1
}

suc(){
	printf "\033[38;5;2m%b\033[0m\n" "${1}"
}

if [ -w "/storage/emulated/0" ]; then
		[ -d "${app_readable_dir}" ] || mkdir "${app_readable_dir}"
		[ -e "${app_readable_dir}/var.log" ] && : > "${app_readable_dir}/var.log"
	else
		err 'Exception: "/storage/emulated/0" is unwritable, make sure you have storage permission'
fi

show_help(){
	while IFS= read -r line; do
		printf "%b\n" "${line}"
	done <<-EOF
	Program that lets you pass argument to mpv-android.
	
	 Usage:
	    ${0##*/} [URL|-] <args>
	    ${0##*/} -v | -h | -l
		
	 Options:
	    -v Print Version and Exit
	    -h Print Help
	    -l Dump Log in stdout (default: disabled)
		
	Use "-" to receive url from stdin.
	"--http-header-fields" headers was delimited using "|".
	
	More info: <https://mpv.io/>.
	Check out manual: <https://mpv.io/manual/master/>.
	EOF
}

# main
mainstripper(){
	printf '%s\n' "${@}" | \
	sed -E 's_---__g	
	s_--__g' | \
	sed -E "/^(file:\/\/|http:\/\/|https:\/\/|ytdl:\/\/|smb:\/\/|bd:\/\/)|^-$|^-(h|v|l)$/d
	s_[\]__g
	s_\x27__g
	s_\x22__g
	/.*=/ {
		s_(=)(.*)_\1\x22\2\x22_
		s_[[:space:]]\x22\$_\x22_g
	}
	/msg-level/ {
		s_\x22__g
	}
	/http-header/ {
		s_\x22__g
		s_(=)(.*)_\1\x27\2\x27_
		s_\|_\x27, \x27_g
	}
	s_[[:space:]]\$__g
	s_\x27[[:space:]]_\x27_g"
}

inter_loop(){
	saveterm="$(stty -g)"
	stty -echo -icanon min 1 time 0
	tail -f "${app_readable_dir}/var.log" 2>/dev/null | grep --line-buffer -v "vo/gpu/opengl" &
	trap "stty ""$saveterm"" && killall -9 tail && exit 1" INT HUP
	while true; do
		sleep 3
		if grep -Pq '\[(main|cplayer)\] (Exiting.*|.*quit\,)' "${app_readable_dir}/var.log"; then
			stty "${saveterm}"
			killall -9 tail
			exit 0
		fi
	done
}

start_mpv(){
	for iter; do
		if printf '%s' "${iter}" | grep -qEo "^(file:\/\/|http:\/\/|https:\/\/|ytdl:\/\/|smb:\/\/|bd:\/\/)[^'\"<>]*|^-$"; then
			[ "${iter}" = "-" ] && set -- "${stdinurl}" && break
			set -- "${iter}" && break
		fi
	done
	[ -z "${1}" ] && err 'Exception: No Video URL provided'
	if ! printf '%s' "${1}" | grep -qEo "(file:\/\/|http:\/\/|https:\/\/|ytdl:\/\/|smb:\/\/|bd:\/\/)[^'\"<>]*"; then
		err 'Invalid type of URL'
	fi
	am start --user current -R 2 -a android.intent.action.VIEW -d "${1}" -n 'is.xyz.mpv/.MPVActivity' >/dev/null 2>&1
	suc "Video Successfully Launched!"
	# Delay to start activity first before clearing the temp file
	nohup "$(sleep 5 && : > "${app_readable_file}")" > /dev/null 2>&1 &
	if [ "${show_log}" = "true" ]; then
		inter_loop
	fi
}

arg_parser(){
	for arg; do
		case "${arg}" in
			-v)
				printf '%s\n' "Version: ${VERSION}"
				exit 0
				;;
			-h)
				show_help
				exit 0
				;;
			-l)
				show_log="true"
				;;
		esac
	done
}

arg_parser "${@}"
mainstripper "${@}" "--log-file=${app_readable_dir}/var.log" > "${app_readable_file}"
start_mpv "${@}"
